create table qin.alumno (padron varchar(255) not null, id bigint not null, primary key (id), unique (padron)) ENGINE=InnoDB;
create table qin.alumno_materia (alumno_id bigint not null, materia_id bigint not null, unique (alumno_id, materia_id)) ENGINE=InnoDB;
create table qin.consigna (id bigint not null auto_increment, consigna varchar(255) not null, orden integer not null, puntaje double precision not null, trabajo_practico_id bigint, primary key (id), unique (id, trabajo_practico_id)) ENGINE=InnoDB;
create table qin.correccion (id bigint not null auto_increment, correccion varchar(255) not null, puntaje double precision not null, dictamen_id bigint, respuesta_id bigint, primary key (id), unique (dictamen_id, respuesta_id)) ENGINE=InnoDB;
create table qin.dictamen (id bigint not null auto_increment, dictamen varchar(255) not null, puntaje double precision not null, resolucion_id bigint, primary key (id), unique (resolucion_id)) ENGINE=InnoDB;
create table qin.docente (matricula varchar(255) not null, id bigint not null, primary key (id), unique (matricula)) ENGINE=InnoDB;
create table qin.grupo (id bigint not null auto_increment, materia_id bigint, resolucion_id bigint, primary key (id), unique (resolucion_id)) ENGINE=InnoDB;
create table qin.grupo_alumno (grupo_id bigint not null, alumno_id bigint not null, unique (grupo_id, alumno_id)) ENGINE=InnoDB;
create table qin.materia (id bigint not null auto_increment, anio bigint not null, carrera varchar(255) not null, codigo varchar(255) not null, cuatrimestre integer not null, nombre varchar(255) not null, docente_id bigint, primary key (id), unique (anio, cuatrimestre, carrera)) ENGINE=InnoDB;
create table qin.resolucion (id bigint not null auto_increment, trabajo_practico_id bigint, primary key (id)) ENGINE=InnoDB;
create table qin.respuesta (id bigint not null auto_increment, respuesta varchar(255) not null, consigna_id bigint, resolucion_id bigint, primary key (id), unique (resolucion_id, consigna_id)) ENGINE=InnoDB;
create table qin.trabajo_practico (id bigint not null auto_increment, titulo varchar(255) not null, materia_id bigint, primary key (id)) ENGINE=InnoDB;
create table qin.usuario (id bigint not null auto_increment, apellido varchar(255) not null, contrasenia_usuario varchar(255) not null, nombre varchar(255) not null, nombre_usuario varchar(255) not null, primary key (id), unique (nombre_usuario)) ENGINE=InnoDB;
alter table qin.alumno add index FKABAED504EF37BA43 (id), add constraint FKABAED504EF37BA43 foreign key (id) references qin.usuario (id);
alter table qin.alumno_materia add index FK1DCACFAA13D0E594 (materia_id), add constraint FK1DCACFAA13D0E594 foreign key (materia_id) references qin.materia (id);
alter table qin.alumno_materia add index FK1DCACFAAC3184200 (alumno_id), add constraint FK1DCACFAAC3184200 foreign key (alumno_id) references qin.alumno (id);
alter table qin.consigna add index FKDE22FA0290D51443 (trabajo_practico_id), add constraint FKDE22FA0290D51443 foreign key (trabajo_practico_id) references qin.trabajo_practico (id);
alter table qin.correccion add index FK44DA650F2EA8FD34 (respuesta_id), add constraint FK44DA650F2EA8FD34 foreign key (respuesta_id) references qin.respuesta (id);
alter table qin.correccion add index FK44DA650F720C6720 (dictamen_id), add constraint FK44DA650F720C6720 foreign key (dictamen_id) references qin.dictamen (id);
alter table qin.dictamen add index FKF5E3FE8B56134460 (resolucion_id), add constraint FKF5E3FE8B56134460 foreign key (resolucion_id) references qin.resolucion (id);
alter table qin.docente add index FK6CFBBE12EF37BA43 (id), add constraint FK6CFBBE12EF37BA43 foreign key (id) references qin.usuario (id);
alter table qin.grupo add index FK5E10C6913D0E594 (materia_id), add constraint FK5E10C6913D0E594 foreign key (materia_id) references qin.materia (id);
alter table qin.grupo add index FK5E10C6956134460 (resolucion_id), add constraint FK5E10C6956134460 foreign key (resolucion_id) references qin.resolucion (id);
alter table qin.grupo_alumno add index FK4193AD9A58A29D94 (grupo_id), add constraint FK4193AD9A58A29D94 foreign key (grupo_id) references qin.grupo (id);
alter table qin.grupo_alumno add index FK4193AD9AC3184200 (alumno_id), add constraint FK4193AD9AC3184200 foreign key (alumno_id) references qin.alumno (id);
alter table qin.materia add index FK321F97E5E7AB9A74 (docente_id), add constraint FK321F97E5E7AB9A74 foreign key (docente_id) references qin.docente (id);
alter table qin.resolucion add index FKA099BE5D90D51443 (trabajo_practico_id), add constraint FKA099BE5D90D51443 foreign key (trabajo_practico_id) references qin.trabajo_practico (id);
alter table qin.respuesta add index FK8B7BEBC056134460 (resolucion_id), add constraint FK8B7BEBC056134460 foreign key (resolucion_id) references qin.resolucion (id);
alter table qin.respuesta add index FK8B7BEBC0139C9FC0 (consigna_id), add constraint FK8B7BEBC0139C9FC0 foreign key (consigna_id) references qin.consigna (id);
alter table qin.trabajo_practico add index FK4B78289D13D0E594 (materia_id), add constraint FK4B78289D13D0E594 foreign key (materia_id) references qin.materia (id);